# -*- coding: utf-8 -*-
from . import auth
from . import model__report
from . import model__loyalty_program
from . import model__loyalty_reward
from . import model__loyalty_rule
from . import model__pos_wallet
from . import model__pos_wallet_transaction
from . import model__pos_wallet_conf
from . import model__pos_wallet_cancellation
from . import model__recharge_rule_list
from . import model__loyalty_gift_history
from . import model__res_partner
from . import model__member_config
from . import model__res_users
from . import model__one_signal_notification_message
from . import model__wallet_gift
from . import model__gift_card
from . import model__pos_category
from . import model__weight_barcode
from . import model__maintenance_equipment
from . import model__product_product
from . import model__pos_config
from . import model__res_city
from . import model__res_township
from . import model__res_country_state
from . import model__coupon_program
from . import model__shop_information
from . import model__pos_order
from . import model__pos_order_line
from . import model__firebase_notification_message
from . import model__special_terms
from . import model__login_popup
from . import model__multi_banners
